/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.text.Normalizer;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import methode.me;

/**
 *
 * @author m.j
 */
public class cal extends javax.swing.JFrame {

    private me m;
    private String result;
    private String last;
    private boolean q;
    private String number;

    /**
     *
     */
    public cal() {
        m = new me();
        number = "";
        result = "";
        last = "";
        q = false;
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        setLocation(new Point((screenSize.width - frameSize.width) / 2,
                (screenSize.height - frameSize.width) / 2));
        this.setResizable(false);
    initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ziro = new javax.swing.JButton();
        equel = new javax.swing.JButton();
        one = new javax.swing.JButton();
        tree = new javax.swing.JButton();
        two = new javax.swing.JButton();
        six = new javax.swing.JButton();
        five = new javax.swing.JButton();
        four = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        text = new javax.swing.JTextField();
        sum = new javax.swing.JButton();
        div = new javax.swing.JButton();
        str = new javax.swing.JButton();
        sub = new javax.swing.JButton();
        beComeZiro = new javax.swing.JButton();

        jButton9.setText("1");

        jButton10.setText("1");

        jButton11.setText("1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));
        setMaximumSize(new java.awt.Dimension(0, 0));

        ziro.setText("0");
        ziro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ziroActionPerformed(evt);
            }
        });

        equel.setText("=");
        equel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equelActionPerformed(evt);
            }
        });

        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        tree.setText("3");
        tree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeActionPerformed(evt);
            }
        });

        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textActionPerformed(evt);
            }
        });

        sum.setText("+");
        sum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumActionPerformed(evt);
            }
        });

        div.setText("/");
        div.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divActionPerformed(evt);
            }
        });

        str.setText("*");
        str.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                strActionPerformed(evt);
            }
        });

        sub.setText("-");
        sub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subActionPerformed(evt);
            }
        });

        beComeZiro.setText("c");
        beComeZiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beComeZiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ziro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tree, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(equel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .addComponent(beComeZiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(text, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sub, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(str, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(39, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(div, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sum, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(str, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sub, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(one, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(two, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tree, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(beComeZiro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(equel, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(ziro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textActionPerformed

    private void treeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeActionPerformed
        // TODO add your handling code here:
     if (q == false) {
            if (result.equals("")) {
                number = number + '3';
                text.setText(number);

            } else {
                number = "";
                number = number + '3';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '3';
                text.setText(number);

            } else {
                number = "";
                number = number + '3';
                text.setText(number);
                result = "";
                
            }
            q = false;
        }
       
       
    }//GEN-LAST:event_treeActionPerformed
    
    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        // TODO add your handling code here:
        if (q == false) {
            if (result.equals("")) {
                number = number + '1';
                text.setText(number);

            } else {
                number = "";
                number = number + '1';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '1';
                text.setText(number);

            } else {
                number = "";
                number = number + '1';
                text.setText(number);
                result = "";
                
            }
             q = false;
        }
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        // TODO add your handling code here:
        if (q == false) {
            if (result.equals("")) {
                number = number + '2';
                text.setText(number);

            } else {
                number = "";
                number = number + '2';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '2';
                text.setText(number);

            } else {
                number = "";
                number = number + '2';
                text.setText(number);
                result = "";
               
            }
             q = false;
        }
    }//GEN-LAST:event_twoActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        // TODO add your handling code here:
       if (q == false) {
            if (result.equals("")) {
                number = number + '4';
                text.setText(number);

            } else {
                number = "";
                number = number + '4';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '4';
                text.setText(number);

            } else {
                number = "";
                number = number + '4';
                text.setText(number);
                result = "";
               
            }
             q = false;
        }
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        // TODO add your handling code here:
      if (q == false) {
            if (result.equals("")) {
                number = number + '5';
                text.setText(number);

            } else {
                number = "";
                number = number + '5';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '5';
                text.setText(number);

            } else {
                number = "";
                number = number + '5';
                text.setText(number);
                result = "";
               
            }
             q = false;
        }
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        // TODO add your handling code here:
        if (q == false) {
            if (result.equals("")) {
                number = number + '6';
                text.setText(number);

            } else {
                number = "";
                number = number + '6';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '6';
                text.setText(number);

            } else {
                number = "";
                number = number + '6';
                text.setText(number);
                result = "";
            
            }
             q = false;
        }
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        // TODO add your handling code here:
        if (q == false) {
            if (result.equals("")) {
                number = number + '7';
                text.setText(number);

            } else {
                number = "";
                number = number + '7';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '7';
                text.setText(number);

            } else {
                number = "";
                number = number + '7';
                text.setText(number);
                result = "";
               
            }
             q = false;
        }
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        // TODO add your handling code here:
        if (q == false) {
            if (result.equals("")) {
                number = number + '8';
                text.setText(number);

            } else {
                number = "";
                number = number + '8';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '8';
                text.setText(number);

            } else {
                number = "";
                number = number + '8';
                text.setText(number);
                result = "";
               
            }
             q = false;
        }
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        // TODO add your handling code here:
        if (q == false) {
            if (result.equals("")) {
                number = number + '9';
                text.setText(number);

            } else {
                number = "";
                number = number + '9';
                text.setText(number);
                result = "";

            }
        } else {
            number = "";
            if (result.equals("")) {
                number = number + '9';
                text.setText(number);

            } else {
                number = "";
                number = number + '9';
                text.setText(number);
                result = "";
                
            }
             q = false;
        }
    }//GEN-LAST:event_nineActionPerformed

    private void beComeZiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beComeZiroActionPerformed
        // TODO add your handling code here:
        number = "0";
        text.setText(number);
        number = "";
    }//GEN-LAST:event_beComeZiroActionPerformed

    private void ziroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ziroActionPerformed
        // TODO add your handling code here:
        if (number.equals("") || number.equals("0")) {
            number = "0";
            text.setText(number);
            number = "";
        } else {
            number = number + '0';
            text.setText(number);
        }
    }//GEN-LAST:event_ziroActionPerformed

    private void equelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equelActionPerformed
        // TODO add your handling code here:
          q = true;
        if (m.search(number) == false) {
            boolean t = false;
            for (int j = 0; j < number.length(); j++) {
                if (number.charAt(j) == '+' || number.charAt(j) == '-' || number.charAt(j) == '*' || number.charAt(j) == '/') {
                    last = number;
                    t = true;
                }
            }
            if (t == true) {
                String s = m.calEquale(number, result, last);
                text.setText(s);
                number = s;
            } else {
                String s = m.calEquale(number, result, last);
                text.setText(s);
                char sign = 0;

                String q;
                for (int i = 0; i < last.length(); i++) {
                    if (last.charAt(i) == '+' || last.charAt(i) == '-' || last.charAt(i) == '*' || last.charAt(i) == '/') {
                        sign = last.charAt(i);
                    }
                }
                int a = last.indexOf(sign);
                q = last.substring(a + 1);
                last = number + sign + q;
                number = s;
            }

        }

      

    }//GEN-LAST:event_equelActionPerformed

    private void sumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumActionPerformed
        // TODO add your handling code here:
       if(number.equals("")==false){
        if (m.search(number) == false) {
            String s = m.compare(number);

            if (number.equals(s)) {
                number += "+";
                text.setText(number);
                result = "";

            } else {
                number = s;
                result = s;
            text.setText(number);
            }

            text.setText(number);
        }
       q=false;
       }
       
    }//GEN-LAST:event_sumActionPerformed

    private void subActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subActionPerformed
        // TODO add your handling code here:
        
        if(number.equals("")==false){
            if (m.search(number) == false) {
            String s = m.compare(number);
            if (number.equals(s)) {
                number += "-";
                text.setText(number);
                result = "";
            } else {
                number = s;
                result = s;
            text.setText(number);
            }

            
    }//GEN-LAST:event_subActionPerformed
    q = false;
        }
    }
    private void divActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divActionPerformed
        // TODO add your handling code here:
       if(number.equals("")==false){
        if (m.search(number) == false) {
            String s = m.compare(number);
            if (number.equals(s)) {
                number += "/";
                text.setText(number);
                result = "";
            } else {
                number = s;
                result = s;
           
             text.setText(number);}

           
    }//GEN-LAST:event_divActionPerformed
    q = false;
       }
    }
    private void strActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_strActionPerformed
        // TODO add your handling code here:
       if(number.equals("")==false){
        if (m.search(number) == false) {
            String s = m.compare(number);
            if (number.equals(s)) {
                number += "*";
                text.setText(number);
                result = "";
            } else {
                number = s;
                result = s;
           text.setText(number);
            }

            
    }//GEN-LAST:event_strActionPerformed
    q = false;
       }
      
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        UIManager.setLookAndFeel(new WindowsLookAndFeel());
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton beComeZiro;
    private javax.swing.JButton div;
    private javax.swing.JButton eight;
    private javax.swing.JButton equel;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton str;
    private javax.swing.JButton sub;
    private javax.swing.JButton sum;
    private javax.swing.JTextField text;
    private javax.swing.JButton tree;
    private javax.swing.JButton two;
    private javax.swing.JButton ziro;
    // End of variables declaration//GEN-END:variables
}
